package net.sf.anathema.hero.template.parser;

import net.sf.anathema.character.main.template.TemplateType;
import net.sf.anathema.hero.dummy.DummyMundaneCharacterType;
import net.sf.anathema.character.main.xml.GenericCharacterTemplate;
import net.sf.anathema.character.main.xml.presentation.GenericPresentationTemplate;
import net.sf.anathema.lib.util.SimpleIdentifier;
import org.junit.Assert;
import org.junit.Test;

public class GenericPresentationPropertiesTest {

  private final GenericPresentationTemplate template = new GenericPresentationTemplate();

  @Test
  public void defaultAutoGeneratedNewResource() throws Exception {
    setTemplateType(new TemplateType(new DummyMundaneCharacterType()));
    assertExpectedResource("CharacterGenerator.Templates.Dummy.TemplateType.Default");
  }

  @Test
  public void subtypedAutoGeneratedNewResource() throws Exception {
    setTemplateType(new TemplateType(new DummyMundaneCharacterType(), new SimpleIdentifier("HeroicSubtype")));
    assertExpectedResource("CharacterGenerator.Templates.Dummy.HeroicSubtype");
  }

  private void setTemplateType(TemplateType templateType) {
    GenericCharacterTemplate dummyCharacterTemplate = new GenericCharacterTemplate();
    dummyCharacterTemplate.setTemplateType(templateType);
    template.setParentTemplate(dummyCharacterTemplate);
  }

  private void assertExpectedResource(String expected) {
    Assert.assertEquals(expected, template.getNewActionResource());
  }
}