package net.sf.anathema.test.character.generic.framework.xml;

import net.sf.anathema.character.generic.framework.xml.presentation.GenericPresentationTemplate;
import net.sf.anathema.character.generic.template.TemplateType;
import net.sf.anathema.dummy.character.template.DummyCharacterTemplate;
import net.sf.anathema.lib.util.Identificate;
import net.sf.anathema.character.generic.type.CharacterType;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class GenericPresentationPropertiesTest {

  private GenericPresentationTemplate template;

  @Before
  public void setUp() throws Exception {
    template = new GenericPresentationTemplate();
  }

  @Test
  public void testAutoGeneratedNewResource() throws Exception {
    DummyCharacterTemplate dummyCharacterTemplate = new DummyCharacterTemplate();
    template.setParentTemplate(dummyCharacterTemplate);
    Assert.assertEquals("CharacterGenerator.Templates.Mortal.TemplateType.Default", template.getNewActionResource()); //$NON-NLS-1$
    dummyCharacterTemplate.setTemplateType(new TemplateType(CharacterType.MORTAL, new Identificate("HeroicSubtype"))); //$NON-NLS-1$
    Assert.assertEquals("CharacterGenerator.Templates.Mortal.HeroicSubtype", template.getNewActionResource()); //$NON-NLS-1$
  }
}
