package net.sf.anathema.hero.template.parser;

import net.sf.anathema.character.main.template.TemplateType;
import net.sf.anathema.character.main.xml.GenericCharacterTemplate;
import net.sf.anathema.character.main.xml.presentation.GenericPresentationTemplate;
import net.sf.anathema.hero.dummy.DummyMundaneCharacterType;
import net.sf.anathema.lib.util.SimpleIdentifier;
import org.junit.Assert;
import org.junit.Test;

public class GenericPresentationPropertiesTest {

  @Test
  public void defaultAutoGeneratedNewResource() throws Exception {
    GenericPresentationTemplate template = setTemplateType(new TemplateType(new DummyMundaneCharacterType()));
    assertExpectedResource(template, "CharacterGenerator.Templates.Dummy.TemplateType.Default");
  }

  @Test
  public void subtypedAutoGeneratedNewResource() throws Exception {
    GenericPresentationTemplate template = setTemplateType(new TemplateType(new DummyMundaneCharacterType(), new SimpleIdentifier("HeroicSubtype")));
    assertExpectedResource(template, "CharacterGenerator.Templates.Dummy.HeroicSubtype");
  }

  private GenericPresentationTemplate setTemplateType(TemplateType templateType) {
    GenericCharacterTemplate dummyCharacterTemplate = new GenericCharacterTemplate();
    dummyCharacterTemplate.setTemplateType(templateType);
    return new GenericPresentationTemplate(dummyCharacterTemplate);
  }

  private void assertExpectedResource(GenericPresentationTemplate template, String expected) {
    Assert.assertEquals(expected, template.getNewActionResource());
  }
}