package net.sf.anathema.namegenerator.exalted.domain;

public interface IVoidstateTokenCollection {

  String[] COLOR_TOKENS = { "Alabaster",
      "Amber",
      "Amythest",
      "Ashen",
      "Azure",
      "Black",
      "Bright",
      "Brilliant",
      "Cerulean",
      "Citrine",
      "Crimson",
      "Ebon",
      "Flaxen",
      "Golden",
      "Grey",
      "Pale",
      "Quicksilver",
      "Radiant",
      "Saffron",
      "Scarlet",
      "Shadowy",
      "Silver",
      "Vermillion",
      "Violet",
      "White"
  };
  String[] CONDITION_TOKENS = { "Condition",
      "Adamant",
      "Blazing",
      "Blind",
      "Celestial",
      "Distant",
      "Drunken",
      "Elder",
      "Empty",
      "Eyeless",
      "Final",
      "First and Forsaken",
      "Flaming",
      "Forsaken",
      "Hidden",
      "Hungry",
      "Invisible",
      "Last",
      "Masked",
      "Ravenous",
      "Secret",
      "Silent",
      "Veiled",
      "Weeping",
      "Whispering" };
  String[] EMOTION_NEGATIVE_TOKENS = { "Bitter",
      "Blighted",
      "Deadly",
      "Death",
      "Dirgeful",
      "Ferocious",
      "Funereal",
      "Grieving",
      "Grievious",
      "Hateful",
      "Poison",
      "Rancourous",
      "Sad",
      "Savage",
      "Sorrowful",
      "Sour",
      "Unrepentant",
      "Vengeful",
      "Venomous",
      "Wrathful" };
  String[] EMOTION_POSITIVE_TOKENS = { "Auspicious",
      "Benificent",
      "Blessed",
      "Bounteous",
      "Exaltant",
      "Excellent",
      "Flawless",
      "Harmonious",
      "Heavenly",
      "Incomparable",
      "Joyous",
      "Jubilant",
      "Perfect",
      "Sagacious",
      "Silken",
      "Virtuous" };
  String[] HEROIC_TOKENS = { "Battleworn",
      "Glorious",
      "Great",
      "Invincible",
      "Mighty",
      "Stalwart",
      "Triumphal",
      "Triumphant",
      "Unconquered",
      "Undefeated",
      "Victorious" };

  String[] MOVEMENT_TOKENS = { "Ascending",
      "Descending",
      "Flickering",
      "Flowing",
      "Fluttering",
      "Leaping",
      "Running",
      "Soaring",
      "Still",
      "Towering",
      "Unfettered",
      "Wandering" };
  String[] NUMBER_TOKENS = { "Eighth",
      "Eleventh",
      "Fifth",
      "First",
      "Fourth",
      "Last",
      "Ninth",
      "Number One",
      "Number Ten",
      "One Hundredth",
      "One Thousandth",
      "Second",
      "Seventh",
      "Sixth",
      "Ten Thousandth",
      "Tenth",
      "Third",
      "Twentieth" };
  String[] ANIMAL_TOKENS = { "Bat",
      "Bear",
      "Bull",
      "Carp",
      "Coyote",
      "Crane",
      "Cricket",
      "Crow",
      "Dog",
      "Dolphin",
      "Dragon",
      "Eagle",
      "Ghost",
      "Hyena",
      "Jackal",
      "Leopard",
      "Lion",
      "Locust",
      "Mammoth",
      "Mantis",
      "Monkey",
      "Owl",
      "Ox",
      "Panther",
      "Phoenix",
      "Rat",
      "Raven",
      "Scarab",
      "Serpent",
      "Shark",
      "Snake",
      "Spider",
      "Tiger",
      "Viper",
      "Vulture",
      "Wolf" };
  String[] BODY_PART_TOKENS = { "Blood",
      "Claw",
      "Eyes",
      "Face",
      "Finger",
      "Fist",
      "Hand",
      "Heart",
      "Mind",
      "Nail",
      "Silhouette",
      "Soul",
      "Stance",
      "Tooth",
      "Wing" };
  String[] BUILDING_TOKENS = { "Bier",
      "Catacomb",
      "Citadel",
      "Demesne",
      "Forge",
      "Fortress",
      "Gate",
      "Keep",
      "Kingdom",
      "Labyrinth",
      "Manse",
      "Monastary",
      "Monolith",
      "Obelisk",
      "Pillar",
      "Prison",
      "Rampart",
      "Redoubt",
      "Refuge",
      "Ruin",
      "Spire",
      "Temple",
      "Tomb",
      "Tower",
      "Vault" };
  String[] CELESTIAL_BODY_TOKENS = { "Cloud",
      "Heaven",
      "Heavens",
      "Horizon",
      "Moon",
      "Rainbow",
      "Sky",
      "Star",
      "Starfall",
      "Sun",
      "Sunrise",
      "Void",
      "Wyld" };
  String[] CHARM_GENERAL_TOKENS = { "Attack",
      "Attitude",
      "Discipline",
      "Evasion",
      "Exercise",
      "Form",
      "Glance",
      "Intuition",
      "Invigoration",
      "Meditation",
      "Method",
      "Prana",
      "Spirit",
      "Stance",
      "Style",
      "Technique",
      "Temper",
      "Understanding" };
  String[] CHARM_COMBAT_TOKENS = { "Attack",
      "Block",
      "Blow",
      "Counterattack",
      "Evasion",
      "Fist",
      "Form",
      "Hammer",
      "Kick",
      "Prana",
      "Stance",
      "Strike",
      "Technique",
      "Throw" };
  String[] LOCATION_TOKENS = { "City",
      "Depths",
      "East",
      "Forests",
      "Heavens",
      "Land",
      "Mountains",
      "North",
      "Oceans",
      "Seas",
      "Sky",
      "South",
      "Underworld",
      "Wasteland",
      "Waves",
      "West",
      "Woods" };
  String[] METAL_STONE_TOKENS = { "Bronze",
      "Copper",
      "Granite",
      "Iron",
      "Iron",
      "Metal",
      "Obsidian",
      "Onyx",
      "Ore",
      "Steel",
      "Stone" };
  String[] NATURAL_OBJECT_TOKENS = { "Blossom",
      "Boulder",
      "Cliff",
      "Dawn",
      "Day",
      "Dusk",
      "Forest",
      "Frost",
      "Garden",
      "Hill",
      "Ice",
      "Iceflow",
      "Lightning",
      "Lotus",
      "Midnight",
      "Mist",
      "Monsoon",
      "Mountain",
      "Night",
      "Oak",
      "Ocean",
      "Orchid",
      "Paradise",
      "Rainbow",
      "Reed",
      "River",
      "Rose",
      "Skies",
      "Sky",
      "Storm",
      "Thunder",
      "Thunderhead",
      "Tsunami",
      "Twilight",
      "Waterfall",
      "Willow",
      "Wind" };
  String[] NEGATIVE_TOKENS = { "Abyss",
      "Anger",
      "Ash",
      "Ashes",
      "Bitterness",
      "Death",
      "Dirge",
      "Dust",
      "Havoc",
      "Loss",
      "Misery",
      "Oblivion",
      "Pain",
      "Plague",
      "Sadness",
      "Vengeance",
      "Venom",
      "Wrath" };
  String[] PERSON_TOKENS = { "Assassin",
      "Bodhissatva",
      "Bureaucrat",
      "Empress",
      "Guardian",
      "Hero",
      "Hunter",
      "Killer",
      "King",
      "Lord",
      "Lover",
      "Maiden",
      "Master",
      "Prince",
      "Princess",
      "Queen",
      "Sage",
      "Scholar",
      "Tyrant",
      "Warrior" };
  String[] PRECIOUS_MATERIAL_TOKENS = { "Crystal",
      "Diamond",
      "Emerald",
      "Gemstone",
      "Glass",
      "Ivory",
      "Jade",
      "Moonsilver",
      "Moonstone",
      "Oricalchum",
      "Platinum",
      "Ruby",
      "Sapphire",
      "Silk",
      "Soulsteel",
      "Starmetal" };
  String[] RELATION_TOKENS = { "Ally",
      "Child",
      "Daimyo",
      "Daughter",
      "Father",
      "Lord",
      "Master",
      "Mother",
      "Ovalisque",
      "Serf",
      "Servant",
      "Slave",
      "Son" };
  String[] WEAPON_TOKENS = { "Axe",
      "Blade",
      "Bow",
      "Fist",
      "Gauntlet",
      "Hammer",
      "Knife",
      "Lance",
      "Shield",
      "Spear",
      "Staff",
      "Sword" };
  String[] DESTROYING_TOKENS = { "Breaking",
      "Consuming",
      "Crushing",
      "Destroying",
      "Devouring",
      "Piercing",
      "Scorning",
      "Smashing",
      "Smiting",
      "Stealing",
      "Sundering",
      "Tearing",
      "Thrashing" };
  String[] LOVING_TOKENS = { "Esteeming",
      "Glorifying",
      "Kissing",
      "Loving",
      "Praising",
      "Treasuring",
      "Worshipping" };
}